version: 2
updates:
- package-ecosystem: gradle
  directories:
    - "/components/abstractions/android"
    - "/components/serialization/form/android"
    - "/components/serialization/json/android"
    - "/components/serialization/text/android"
    - "/components/serialization/multipart/android"
    - "/components/authentication/azure/android"
    - "/components/http/okHttp/android"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
