version: 2
updates:
- package-ecosystem: gradle
  directories:
    - "/"
    - "/components/abstractions"
    - "/components/serialization/form"
    - "/components/serialization/json"
    - "/components/serialization/text"
    - "/components/serialization/multipart"
    - "/components/authentication/azure"
    - "/components/http/okHttp"
  schedule:
    interval: daily
    time: "09:00" # 9am UTC
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directories:
    - "/components/abstractions/android"
    - "/components/serialization/form/android"
    - "/components/serialization/json/android"
    - "/components/serialization/text/android"
    - "/components/serialization/multipart/android"
    - "/components/authentication/azure/android"
    - "/components/http/okHttp/android"
  schedule:
    interval: daily
    time: "10:00" # 10am UTC. Checked after the core modules to prevent duplicate PRs updating dependencies.gradle files
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
